name: 'Deploy Infrastructure'

on:
  push:
    branches:
      - main
      - develop
      - terraform/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    name: 'Deploy Infrastructure'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Setup Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.0'

    - name: Setup SSH Keys
      run: |
        mkdir -p ~/.ssh/to_azure
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/to_azure/CPEN321.pem
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/to_azure/CPEN321.pub
        chmod 600 ~/.ssh/to_azure/CPEN321.pem
        chmod 644 ~/.ssh/to_azure/CPEN321.pub
        ls -la ~/.ssh/

    - name: Create .env File
      run: |
        echo "PORT=3000" > backend/.env
        echo "DB_URI=mongodb://mongo:27017/biteswipe" >> backend/.env
        echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> backend/.env
        echo "FIREBASE_CREDENTIALS_JSON_PATHNAME=/app/backend/biteswipe-132f1-firebase-adminsdk-fbsvc-76c5bb6fe5.json" >> backend/.env

    - name: Deploy New Infrastructure
      run: |
        cd backend/scripts
        chmod +x import_resource_group.sh
        python3 deploy_infra.py
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
